/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'stm32f103' 
 * Target:  'Target 1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Acceleration:Arm-2D:Core@1.1.7 */
#define ___ARM_2D_CFG_SKIP_HEADER___
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.3.3 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1


#endif /* PRE_INCLUDE_GLOBAL_H */
